INSERT INTO Banda_Artista (nome, estilo, integrantes, tipo)
VALUES
  ('Legião Urbana Cover', 'Rock', 4, 'Banda'),
  ('João Bosco', 'MPB', 1, 'Artista Solo'),
  ('Samba da Lapa', 'Samba', 6, 'Banda'),
  ('Blues Brothers Brasil', 'Blues', 5, 'Banda'),
  ('Marina Lima', 'Pop Rock', 1, 'Artista Solo'),
  ('Os Mutantes Cover', 'Rock Psicodélico', 3, 'Banda'),
  ('Djavan Acústico', 'MPB', 1, 'Artista Solo'),
  ('Raul Seixas Tributo', 'Rock', 4, 'Banda'),
  ('Tom Jobim Experience', 'Jazz', 5, 'Banda'),
  ('Rock n Roll All Stars', 'Rock Clássico', 6, 'Banda'),
  ('Charlie Brown Jr Cover', 'Rock', 4, 'Banda'),
  ('Maria Rita', 'Samba', 1, 'Artista Solo'),
  ('Skank Tributo', 'Pop Rock', 4, 'Banda'),
  ('Toni Garrido', 'Reggae', 1, 'Artista Solo'),
  ('Mamonas Assassinas Cover', 'Rock Cômico', 5, 'Banda'),
  ('Tim Maia Cover', 'Soul', 7, 'Banda'),
  ('Alceu Valença', 'Forró', 1, 'Artista Solo'),
  ('System of a Down Cover', 'Rock Pesado', 4, 'Banda'),
  ('Dj Khaled', 'Hip Hop', 1, 'Artista Solo'),
  ('Cazuza Tributo', 'Rock', 3, 'Banda'),
  ('Festa da Bossa Nova', 'Bossa Nova', 2, 'Banda'),
  ('Pitty', 'Rock', 1, 'Artista Solo'),
  ('Capital Inicial Cover', 'Rock', 4, 'Banda'),
  ('Zé Ramalho', 'Folk', 1, 'Artista Solo'),
  ('Titãs Tributo', 'Rock', 4, 'Banda'),
  ('Banda do Mar Cover', 'Indie', 3, 'Banda'),
  ('O Rappa Tributo', 'Rock', 5, 'Banda'),
  ('Rita Lee Cover', 'Rock', 4, 'Banda'),
  ('Barão Vermelho Cover', 'Rock', 4, 'Banda'),
  ('Caetano Veloso', 'MPB', 1, 'Artista Solo'),
  ('Chico Buarque', 'MPB', 1, 'Artista Solo'),
  ('Gilberto Gil', 'MPB', 1, 'Artista Solo'),
  ('Mutantes do Sertão', 'Forró', 3, 'Banda'),
  ('Marisa Monte', 'MPB', 1, 'Artista Solo'),
  ('Seu Jorge', 'Samba', 1, 'Artista Solo'),
  ('Jorge Ben Jor', 'Samba', 1, 'Artista Solo'),
  ('Tribalistas Tributo', 'MPB', 3, 'Banda'),
  ('Roupa Nova Cover', 'Pop', 5, 'Banda'),
  ('Dj Alok', 'Eletrônica', 1, 'Artista Solo'),
  ('Jota Quest Cover', 'Pop Rock', 5, 'Banda');