INSERT INTO Funcionario (nome, cargo, telefone, id_gerente)
VALUES
  ('Roberto Souza', 'Gerente', '11977776666', NULL);

INSERT INTO Funcionario (nome, cargo, telefone, id_gerente)
VALUES
  ('Carlos Pereira', 'Garçom', '11999998888', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Fernanda Lima', 'Cozinheira', '11988887777', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Ana Oliveira', 'Garçom', '11966665555', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Pedro Santos', 'Barman', '11955554444', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Mariana Costa', 'Garçom', '11944443333', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('João Silva', 'Cozinheiro', '11933332222', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Juliana Ribeiro', 'Garçom', '11922221111', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Rafael Fernandes', 'Barman', '11911110000', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Patrícia Almeida', 'Garçom', '11900009999', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Guilherme Martins', 'Cozinheiro', '11899998888', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Beatriz Nunes', 'Garçom', '11888887777', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Daniel Gomes', 'Garçom', '11877776666', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Leticia Barbosa', 'Cozinheira', '11866665555', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Fábio Rodrigues', 'Barman', '11855554444', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Amanda Silva', 'Garçom', '11844443333', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Thiago Oliveira', 'Cozinheiro', '11833332222', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Larissa Pereira', 'Garçom', '11822221111', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Lucas Fernandes', 'Barman', '11811110000', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Carla Souza', 'Garçom', '11800009999', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Gustavo Lima', 'Cozinheiro', '11799998888', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Camila Costa', 'Garçom', '11788887777', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Ricardo Santos', 'Garçom', '11777776666', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Vivian Mendes', 'Cozinheira', '11766665555', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('André Almeida', 'Barman', '11755554444', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Isabela Ribeiro', 'Garçom', '11744443333', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Felipe Gonçalves', 'Cozinheiro', '11733332222', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Sofia Barbosa', 'Garçom', '11722221111', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Bruno Morais', 'Barman', '11711110000', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Gabriela Castro', 'Garçom', '11700009999', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Eduardo Martins', 'Cozinheiro', '11699998888', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Clara Nunes', 'Garçom', '11688887777', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Marcelo Gomes', 'Garçom', '11677776666', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Larissa Oliveira', 'Cozinheira', '11666665555', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Diego Rodrigues', 'Barman', '11655554444', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Carolina Souza', 'Garçom', '11644443333', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Thiago Lima', 'Cozinheiro', '11633332222', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Vanessa Costa', 'Garçom', '11622221111', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Matheus Santos', 'Barman', '11611110000', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza')),
  ('Beatriz Pereira', 'Garçom', '11600009999', (SELECT id_funcionario FROM Funcionario WHERE nome = 'Roberto Souza'));